//dummy data

class UserData {
  List<Map<String, dynamic>> userData = [
    {
      "sno": 1,
      "name": "User 1",
      "role": "Admin",
      "org": "Organisation 1",
      "geo": "Geography 1",
      "status": "ACTIVE",
    },
    {
      "sno": 2,
      "name": "User 2",
      "role": "Admin",
      "org": "Organisation 2",
      "geo": "Geography 1",
      "status": "ACTIVE",
    },
    {
      "sno": 3,
      "name": "User 3",
      "role": "Logistics",
      "org": "Organisation 1",
      "geo": "Geography 1",
      "status": "ACTIVE",
    },
    {
      "sno": 4,
      "name": "User 4",
      "role": "Transporter",
      "org": "Organisation 2",
      "geo": "Geography 2",
      "status": "INACTIVE",
    },
    {
      "sno": 5,
      "name": "User 5",
      "role": "Admin",
      "org": "Organisation 1",
      "geo": "Geography 3",
      "status": "ACTIVE",
    },
    {
      "sno": 6,
      "name": "User 6",
      "role": "Worker",
      "org": "Organisation 2",
      "geo": "Geography 3",
      "status": "ACTIVE",
    },
    {
      "sno": 7,
      "name": "User 7",
      "role": "Transporter",
      "org": "Organisation 1",
      "geo": "Geography 1",
      "status": "ACTIVE",
    },
    {
      "sno": 8,
      "name": "User 8",
      "role": "Logistics",
      "org": "Organisation 3",
      "geo": "Geography 3",
      "status": "ACTIVE",
    },
    {
      "sno": 9,
      "name": "User 9",
      "role": "Logistics",
      "org": "Organisation 4",
      "geo": "Geography 3",
      "status": "ACTIVE",
    },
    {
      "sno": 10,
      "name": "User 10",
      "role": "Admin",
      "org": "Organisation 2",
      "geo": "Geography 3",
      "status": "INACTIVE",
    },
    {
      "sno": 11,
      "name": "User 11",
      "role": "Transporter",
      "org": "Organisation 4",
      "geo": "Geography 4",
      "status": "ACTIVE",
    },
    {
      "sno": 12,
      "name": "User 12",
      "role": "Logistics",
      "org": "Organisation 3",
      "geo": "Geography 4",
      "status": "ACTIVE",
    },
    {
      "sno": 13,
      "name": "User 13",
      "role": "Admin",
      "org": "Organisation 2",
      "geo": "Geography 2",
      "status": "ACTIVE",
    },
    {
      "sno": 14,
      "name": "User 14",
      "role": "Transporter",
      "org": "Organisation 1",
      "geo": "Geography 1",
      "status": "ACTIVE",
    },
    {
      "sno": 15,
      "name": "User 15",
      "role": "Admin",
      "org": "Organisation 4",
      "geo": "Geography 4",
      "status": "ACTIVE",
    },
    {
      "sno": 16,
      "name": "User 16",
      "role": "Admin",
      "org": "Organisation 4",
      "geo": "Geography 4",
      "status": "ACTIVE",
    },
    {
      "sno": 17,
      "name": "User 17",
      "role": "Admin",
      "org": "Organisation 1",
      "geo": "Geography 5",
      "status": "INACTIVE",
    },
    {
      "sno": 18,
      "name": "User 18",
      "role": "Logistics",
      "org": "Organisation 5",
      "geo": "Geography 3",
      "status": "INACTIVE",
    },
    {
      "sno": 19,
      "name": "User 19",
      "role": "Logistics",
      "org": "Organisation 5",
      "geo": "Geography 3",
      "status": "ACTIVE",
    },
    {
      "sno": 20,
      "name": "User 20",
      "role": "Logistics",
      "org": "Organisation 5",
      "geo": "Geography 3",
      "status": "INACTIVE",
    },
    {
      "sno": 21,
      "name": "User 21",
      "role": "Logistics",
      "org": "Organisation 5",
      "geo": "Geography 3",
      "status": "ACTIVE",
    },
    {
      "sno": 22,
      "name": "User 22",
      "role": "Logistics",
      "org": "Organisation 5",
      "geo": "Geography 3",
      "status": "INACTIVE",
    },
    {
      "sno": 23,
      "name": "User 24",
      "role": "Logistics",
      "org": "Organisation 5",
      "geo": "Geography 3",
      "status": "ACTIVE",
    },
    {
      "sno": 24,
      "name": "User 24",
      "role": "Logistics",
      "org": "Organisation 5",
      "geo": "Geography 3",
      "status": "INACTIVE",
    },
    {
      "sno": 25,
      "name": "User 25",
      "role": "Logistics",
      "org": "Organisation 5",
      "geo": "Geography 3",
      "status": "ACTIVE",
    },
    {
      "sno": 26,
      "name": "User 26",
      "role": "Logistics",
      "org": "Organisation 5",
      "geo": "Geography 3",
      "status": "INACTIVE",
    },
    {
      "sno": 27,
      "name": "User 27",
      "role": "Logistics",
      "org": "Organisation 5",
      "geo": "Geography 3",
      "status": "ACTIVE",
    },
    {
      "sno": 28,
      "name": "User 28",
      "role": "Logistics",
      "org": "Organisation 5",
      "geo": "Geography 3",
      "status": "ACTIVE",
    },
    {
      "sno": 29,
      "name": "User 29",
      "role": "Logistics",
      "org": "Organisation 5",
      "geo": "Geography 3",
      "status": "INACTIVE",
    },
    {
      "sno": 30,
      "name": "User 30",
      "role": "Logistics",
      "org": "Organisation 5",
      "geo": "Geography 3",
      "status": "ACTIVE",
    },
  ];
}
